---
- name: debug facts
  hosts: loadbalancer
  tasks: 
  - name: Print all gathered facts
    debug:
      var: ansible_facts

- name: Konfigurieren des Load Balancers
  hosts: loadbalancer
  become: yes
  roles:
    - nginx_loadbalancer

- name: Konfigurieren der App-Server
  hosts: app_servers
  become: yes
  roles:
    - nodejs_app
